### ISSUE TITLE
Possible issue with comma requires?

### ISSUE THREAD

**Issue by TatumCreative** [stackgl/glslify#41]
```
var	Glslify		  = require('glslify')
  , CreateVAO	  =	require('gl-vao')
  , CreateBuffer  =	require('gl-buffer')
  , GlShader	  =	require('gl-shader')
  , Extend		  =	require('xtend')
  , Mat4		  =	require('gl-mat4')
```
This threw an error when I had commas and glslify in any order. I changed the next require to have a var and it worked. Using glslify 2.0.1.

```
Error: Parsing file /Users/path/tree-editor/lib/model.js: Unexpected token (5:33)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:398:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:341:48)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:336:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:199:16)
```

**Comment by hughsk** [comment]
Hmm, that's weird... I suspect this is an issue with [static-module](https://github.com/substack/static-module) since that's what's handling `require` hooks now.

**Comment by mattdesl** [comment]
See here:
https://github.com/substack/brfs/issues/28

**Comment by RGBboy** [comment]
I have also found a similar error when I have the following:

``` javascript
var glslify = require('glslify'),
    other;
```

I get the error:
```
TypeError: Cannot read property 'start' of null while parsing file: /Users/XXXX/projects/gl/index.js
    at /Users/XXXX/projects/gl/node_modules/glslify/node_modules/static-module/index.js:139:56
```

It is definitely related to `static-module`. If I write the following all is well:

``` javascript
var glslify = require('glslify');
var other;
```

**Comment by mikolalysenko** [comment]
Could be a bug in static-module.  Any ideas @substack ?
