### ISSUE TITLE
Can't use async/await with browserify+glslify

### ISSUE THREAD

**Issue by wwwtyro** [stackgl/glslify#88]
I've attached a simple repro package that uses async/await functionality.

Basically, if I use browserify alone, it works fine:
```sh
$ npm run test0

> foo@1.0.0 test0 /tmp/foo
> browserify -o bundle.js index.js
```

But if I use it with `-t glslify`, I get acorn errors:
```sh
$ npm run test1

> foo@1.0.0 test1 /tmp/foo
> browserify -o bundle.js index.js -t glslify

SyntaxError: Unexpected token (1:6) while parsing file: /tmp/foo/index.js
    at Parser.pp$4.raise (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.semicolon (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:600:59)
    at Parser.pp$1.parseExpressionStatement (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:1025:8)
    at Parser.pp$1.parseStatement (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:780:22)
    at Parser.pp$1.parseTopLevel (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:672:23)
    at Parser.parse (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:529:15)
    at parse (/tmp/foo/node_modules/falafel/node_modules/acorn/dist/acorn.js:3378:37)
    at module.exports (/tmp/foo/node_modules/falafel/index.js:22:15)
    at /tmp/foo/node_modules/glslify/transform.js:44:22
```

[foo.tar.gz](https://github.com/stackgl/glslify/files/863473/foo.tar.gz)

**Comment by hughsk** [comment]
Oof, that's no good — apparently acorn doesn't support ES7 syntax such as async/await. A quick workaround for your project would be to apply only the async/await babel transform via `babelify` before `glslify`, e.g. something like this:

``` json
{
  "browserify": {
    "transform": [
      ["babelify", {
        "plugins": [
          "transform-async-to-generator"
        ]
      }],
      "glslify"
    ]
  }
}
```

Ideally there's an approach where glslify can deal with the syntax without issue though. Just a matter of finding a parser/setup that can handle it :)

**Comment by wwwtyro** [comment]
@hughsk super helpful, thanks! :heart:
